require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native/virtualized-lists/scripts/cocoapods/helpers.rb'

platform :ios, '13.4'
install! 'cocoapods', :deterministic_uuids => false

target 'AIposter' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'AIposterTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
